@startuml
start
:Прийти на кухню;
:Достать сковороду;
if (Сковорода чистая?) then (Нет)
    :Помыть сковороду;
else (Да)
endif
:Поставить сковороду на плиту;
:Включить плиту;
:Достать подсолнечное масло;
:Налить масло в сковороду;
:Достать яйца из холодильника;
:Помыть яйца;
:Разбить яйца в сковороду;
if (Яйца готовы?) then (Нет)
    :Продолжать жарить;
else (Да)
endif
:Отключить плиту;
:Убрать сковороду с плиты;
end
@enduml